"""empty message

Revision ID: 0bfc95221f25
Revises: 18b3db46bb2b
Create Date: 2018-11-13 03:29:20.196053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bfc95221f25'
down_revision = '18b3db46bb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comment', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_comment_timestamp'), 'post_comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_comment_timestamp'), table_name='post_comment')
    op.drop_column('post_comment', 'timestamp')
    # ### end Alembic commands ###
