"""empty message

Revision ID: 3f87c47bc537
Revises: d93aefe82bbd
Create Date: 2018-11-11 01:01:32.149351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f87c47bc537'
down_revision = 'd93aefe82bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_image', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_image', sa.Column('url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
