"""empty message

Revision ID: d93aefe82bbd
Revises: 07605384c737
Create Date: 2018-11-11 00:53:02.492255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93aefe82bbd'
down_revision = '07605384c737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_image', sa.Column('url', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_image', 'url')
    # ### end Alembic commands ###
