"""adding default to user model

Revision ID: e1bfcb0213ff
Revises: 8c61d81ca352
Create Date: 2018-10-18 20:29:01.455090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bfcb0213ff'
down_revision = '8c61d81ca352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'default')
    # ### end Alembic commands ###
